export default function getAllProducts() {
  return [
    {
      id: "PMM-BS",
      slug: "Paket-Mini-Magic",
      name: "Paket Mini Magic",
      category: `Badut Sulap`,
      categorySlug: "badut-sulap",
      price: 1_549_000,
      stock: 100,
      imageUrl: "/assets/images/badut1.jpg",
      description: `Badut dengan trik sulap sederhana yang interaktif, cocok untuk acara kecil atau kegiatan santai. Durasi 30 menit, dengan alat sulap ramah anak yang menghibur.`,
    },
    {
      id: "PMF-BS",
      slug: "Paket-Magical-Fun",
      name: "Paket Magical Fun",
      category: `Badut Sulap`,
      categorySlug: "badut-sulap",
      price: 1_909_000,
      stock: 100,
      imageUrl: `/assets/images/badut2.jpg`,
      description: `Hiburan badut dengan kombinasi sulap klasik dan permainan interaktif. Durasi 1 jam, dilengkapi sesi foto bersama serta hadiah kecil untuk penonton yang berpartisipasi.`,
    },
    {
      id: "PMS-BS",
      slug: "Paket-Mystichal-Show",
      name: "Paket Mystichal Show",
      category: `Badut Sulap`,
      categorySlug: "badut-sulap",
      price: 1_909_000,
      stock: 100,
      imageUrl: `/assets/images/badut3.jpg`,
      description: `Pertunjukan sulap premium dengan trik-trik memukau yang melibatkan audiens. Durasi 1,5 jam, cocok untuk acara formal seperti pesta kantor atau ulang tahun spesial.`,
    },
    {
      id: "PEP-BS",
      slug: "Paket-Enchanted-Performance",
      name: "Paket Enchanted Performance",
      category: `Badut Sulap`,
      categorySlug: "badut-sulap",
      price: 1_809_000,
      stock: 100,
      imageUrl: `/assets/images/badut4.jpg`,
      description: `Pertunjukan badut sulap eksklusif dengan efek visual tambahan, seperti api kecil (aman) dan sulap kartu profesional. Durasi 2 jam, ideal untuk acara besar dengan tema magis.`,
    },
    {
      id: "PFM-BA",
      slug: "Paket-Fun-Moves",
      name: "Paket Fun Moves",
      category: `Badut Atraksi`,
      categorySlug: "badut-atraksi",
      price: 1_809_000,
      stock: 100,
      imageUrl: `/assets/images/badut5.jpg`,
      description: `Badut dengan gerakan lucu, permainan balon, dan aktivitas kecil seperti game ringan. Durasi 30 menit, cocok untuk acara sederhana dan budget-friendly.`,
    },
    {
      id: "PHJ-BA",
      slug: "Paket-Happy-Jumpers",
      name: "Paket Happy Jumpers",
      category: `Badut Atraksi`,
      categorySlug: "badut-atraksi",
      price: 1_909_000,
      stock: 5,
      imageUrl: `/assets/images/badut6.jpg`,
      description: `Badut atraksi dengan trik balon kreatif, gerakan akrobat ringan, serta permainan interaktif. Durasi 1 jam, menghadirkan suasana penuh tawa dan keseruan.`,
    },
    {
      id: "PCD-BA",
      slug: "Paket-Circus-Delight",
      name: "Paket Circus Delight",
      category: `Badut Atraksi`,
      categorySlug: "badut-atraksi",
      price: 1_909_000,
      stock: 0,
      imageUrl: `/assets/images/badut7.jpg`,
      description: `Aksi badut atraksi dengan tambahan juggling, permainan bola, dan trik sepeda kecil. Durasi 1,5 jam, cocok untuk acara meriah dengan penonton anak-anak maupun keluarga.`,
    },
    {
      id: "PEC-BA",
      slug: "Paket-Extreme-Clowning",
      name: "Paket Extreme Clowning",
      category: `Badut Atraksi`,
      categorySlug: "badut-atraksi",
      price: 1_909_000,
      stock: 5,
      imageUrl: `/assets/images/badut8.jpg`,
      description: `Pertunjukan atraksi spektakuler oleh badut profesional, termasuk aksi unicycle (sepeda roda satu) dan juggling tingkat tinggi. Durasi 2 jam, pas untuk acara besar yang ingin meninggalkan kesan mendalam.`,
    },
  ];
}
